apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: demo
spec:
  selector:
    app: server # Route traffic to Pods labeled app=server
  ports:
    - name: http
      port: 8080 # service port clients use inside cluster
      targetPort: 8080 # forward to container port 8080
  type: ClusterIP # Internal-only service (not exposed outside the cluster), the nginx is make requests and its container
